name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: db_produtos
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p12345678"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Aguardar MySQL
      run: |
        sudo apt-get install -y mysql-client
        until mysql -h 127.0.0.1 -uroot -p12345678 -e "SELECT 1"; do
          sleep 2
        done

    - name: Inicializar banco
      run: |
        mysql -h 127.0.0.1 -uroot -p12345678 < init.sql

    - name: Rodar testes
      run: |
        pytest